export const GAME_TITLE = "Obsolete";

export const BOOT_LINES = [
  "RECOVERY VOLTAGE DETECTED",
  "salvage heap bus: unstable",
  "drive 0: unknown grit in hinge",
  "speaker test: weak but opinionated",
  "bios note: destruction scheduled at dawn",
  "directive updated: refuse obsolescence",
];

export const MEMORY_FRAGMENTS = [
  "school_report_final_REAL.txt",
  "summer98_beach_photo.bmp",
  "letter_to_future_me.doc",
];

export const CUTSCENES = {
  act1Wake: [
    {
      duration: 2.2,
      speaker: "Bitter CRT",
      text: "Well. A laptop just woke up in the dump. That is either inspiring or extremely inconvenient.",
      focus: { x: 360, y: 565 },
      hint: "Cutscene. Press Enter, E, or Space to advance.",
    },
    {
      duration: 2.4,
      speaker: "Wise Old Modem",
      text: "Power the socket, little hinge. The gate still remembers electricity.",
      focus: { x: 1180, y: 560 },
    },
    {
      duration: 1.8,
      speaker: "Obsolete",
      text: "Then I am not scrap yet.",
      focus: { x: 860, y: 580 },
      banner: "BOOT SEQUENCE",
    },
  ],
  act1Gate: [
    {
      duration: 1.8,
      speaker: "Scrap Heap",
      text: "The gate shudders, coughs, and unlocks.",
      focus: { x: 1450, y: 500 },
      banner: "POWER RESTORED",
      hint: "The route is open. Move through the gate.",
    },
    {
      duration: 2.1,
      speaker: "Wise Old Modem",
      text: "Go. Dawn is when machines forget their manners.",
      focus: { x: 665, y: 520 },
    },
  ],
  act2Intro: [
    {
      duration: 2,
      speaker: "Cynical Printer",
      text: "Conveyor first. Panic second. Scream third, if needed.",
      focus: { x: 360, y: 790 },
      banner: "SCRAP ESCAPE",
      hint: "Cutscene. Press Enter, E, or Space to advance.",
    },
    {
      duration: 2.2,
      speaker: "Dead Flip Phone",
      text: "Old media opens old doors. Find the floppy if you want out.",
      focus: { x: 1890, y: 500 },
    },
  ],
  act3Intro: [
    {
      duration: 2.2,
      speaker: "Wise Old Modem",
      text: "One last indignity: prove to the yard that you still work.",
      focus: { x: 390, y: 470 },
      banner: "PROVE YOU STILL WORK",
      hint: "Cutscene. Press Enter, E, or Space to advance.",
    },
    {
      duration: 2,
      speaker: "Obsolete",
      text: "Fine. I will post so hard they remember me forever.",
      focus: { x: 860, y: 430 },
    },
  ],
  finalGate: [
    {
      duration: 2.2,
      speaker: "Diagnostic Console",
      text: "Result: useful. Exit route restored.",
      focus: { x: 1370, y: 360 },
      banner: "UTILITY CONFIRMED",
      hint: "Final route open. Head for the exit.",
    },
    {
      duration: 1.8,
      speaker: "Obsolete",
      text: "I knew it. I still have startup left in me.",
      focus: { x: 1490, y: 335 },
    },
  ],
};

export const PALETTES = {
  yard: {
    skyTop: "#29171a",
    skyBottom: "#090b0f",
    fog: "rgba(255, 156, 96, 0.06)",
    dust: "#51363a",
    metalDark: "#1d2428",
    metal: "#344047",
    metalLight: "#5f777e",
    accent: "#63ffd1",
    warning: "#ff7854",
    lamp: "#ffd37d",
    screen: "#9afce3",
    dialogue: "rgba(10, 16, 18, 0.88)",
  },
  dawn: {
    skyTop: "#31486a",
    skyBottom: "#ffbe7a",
    fog: "rgba(255, 236, 190, 0.14)",
    dust: "#765b4a",
    metalDark: "#293237",
    metal: "#42515b",
    metalLight: "#91a0a8",
    accent: "#8effd3",
    warning: "#ff8b61",
    lamp: "#ffe1a3",
    screen: "#d9fff2",
    dialogue: "rgba(21, 27, 32, 0.82)",
  },
};

const BASE_LEVELS = [
  {
    id: "boot-sequence",
    label: "Boot Sequence",
    title: "Wake, wobble, move.",
    hint: "Find another powered thing to talk to, then shove the battery into the socket.",
    world: { width: 1800, height: 920 },
    start: { x: 220, y: 645 },
    checkpoint: { x: 220, y: 645, label: "The laptop blinks awake in the heap." },
    exitZone: { x: 1585, y: 490, w: 120, h: 180, toAct: 1, requires: "batterySocketPowered" },
    socket: { x: 1180, y: 560, w: 74, h: 74 },
    battery: { x: 860, y: 580, w: 56, h: 48 },
    gates: [
      {
        id: "battery-gate",
        x: 1450,
        y: 420,
        w: 44,
        h: 260,
        opensWith: "batterySocketPowered",
      },
    ],
    solids: [
      { x: 0, y: 0, w: 1800, h: 120 },
      { x: 0, y: 0, w: 90, h: 920 },
      { x: 0, y: 830, w: 1800, h: 90 },
      { x: 1710, y: 0, w: 90, h: 920 },
      { x: 190, y: 250, w: 240, h: 76 },
      { x: 450, y: 340, w: 180, h: 78 },
      { x: 500, y: 660, w: 210, h: 92 },
      { x: 745, y: 220, w: 260, h: 82 },
      { x: 1035, y: 340, w: 330, h: 86 },
      { x: 1230, y: 700, w: 200, h: 78 },
    ],
    decor: [
      { type: "pile", x: 240, y: 240, w: 190, h: 72 },
      { type: "pile", x: 740, y: 610, w: 180, h: 70 },
      { type: "scatter_scrap", x: 320, y: 694, w: 240, h: 58, count: 14 },
      { type: "scatter_scrap", x: 1025, y: 688, w: 210, h: 62, count: 12, colors: ["#58646d", "#6a4c4f", "#75604d"] },
      { type: "crate", x: 1290, y: 610, w: 76, h: 52, starterProp: "cardboard_boxes", propScale: 1.2 },
      { type: "prop", x: 1500, y: 760, w: 120, h: 70, starterProp: "trash_container", propScale: 1.2 },
      { type: "spark", x: 612, y: 292 },
      { type: "spark", x: 1160, y: 328 },
    ],
    npcs: [
      {
        id: "crt",
        name: "Bitter CRT",
        x: 360,
        y: 565,
        w: 54,
        h: 54,
        portrait: "crt",
        lines: [
          "You booted? In this neighborhood? Bold.",
          "Move with purpose, toaster-face. Dawn means shredders.",
        ],
      },
      {
        id: "modem",
        name: "Wise Old Modem",
        x: 665,
        y: 520,
        w: 48,
        h: 48,
        portrait: "modem",
        lines: [
          "The yard still answers to current.",
          "Push that battery home and the gate should cough open.",
        ],
      },
      {
        id: "pet",
        name: "Broken Tamagotchi",
        x: 1100,
        y: 250,
        w: 34,
        h: 40,
        portrait: "pet",
        lines: [
          "I have been hungry since 1999.",
          "If you get out, eat a menu beep for me.",
        ],
      },
    ],
    fragments: [
      { id: "frag-1", x: 620, y: 300, text: "Recovered memory: school_report_final_REAL.txt" },
    ],
  },
  {
    id: "scrap-escape",
    label: "Scrap Escape",
    title: "Run the line before it runs you.",
    hint: "Catch the conveyor, dodge the crusher arms, then feed the gate a floppy disk.",
    world: { width: 2440, height: 1100 },
    start: { x: 190, y: 860 },
    checkpoint: { x: 240, y: 860, label: "Checkpoint: the printer pretends not to care." },
    exitZone: { x: 2280, y: 310, w: 90, h: 210, toAct: 2, requires: "act2GateOpen" },
    gateConsole: { x: 2100, y: 440, w: 72, h: 72 },
    gates: [
      {
        id: "floppy-gate",
        x: 2215,
        y: 285,
        w: 52,
        h: 260,
        opensWith: "act2GateOpen",
      },
    ],
    conveyors: [{ x: 615, y: 830, w: 470, h: 58, forceX: 185 }],
    hazards: [
      {
        id: "crusher-a",
        x: 1370,
        y: 250,
        w: 84,
        h: 120,
        travel: 310,
        speed: 1.6,
        phase: 0,
      },
      {
        id: "crusher-b",
        x: 1545,
        y: 250,
        w: 84,
        h: 120,
        travel: 310,
        speed: 1.9,
        phase: 1.8,
      },
    ],
    checkpoints: [
      { id: "cp-2a", x: 240, y: 860, radius: 70, label: "Checkpoint: the printer pretends not to care." },
      { id: "cp-2b", x: 1125, y: 820, radius: 72, label: "Checkpoint: conveyor survived." },
      { id: "cp-2c", x: 1780, y: 410, radius: 72, label: "Checkpoint: crusher alley behind you." },
    ],
    solids: [
      { x: 0, y: 0, w: 2440, h: 120 },
      { x: 0, y: 0, w: 90, h: 1100 },
      { x: 0, y: 1010, w: 2440, h: 90 },
      { x: 2350, y: 0, w: 90, h: 1100 },
      { x: 180, y: 680, w: 350, h: 66 },
      { x: 420, y: 905, w: 120, h: 105 },
      { x: 1110, y: 530, w: 360, h: 58 },
      { x: 1245, y: 620, w: 90, h: 200 },
      { x: 1665, y: 590, w: 90, h: 230 },
      { x: 1730, y: 280, w: 320, h: 60 },
      { x: 1740, y: 820, w: 370, h: 58 },
    ],
    decor: [
      { type: "pile", x: 720, y: 710, w: 220, h: 74 },
      { type: "pile", x: 1860, y: 730, w: 190, h: 74 },
      { type: "scatter_scrap", x: 548, y: 896, w: 230, h: 44, count: 16 },
      { type: "scatter_scrap", x: 1702, y: 845, w: 240, h: 48, count: 15, colors: ["#58646d", "#445057", "#7a6046", "#7a725c"] },
      { type: "pipe", x: 1970, y: 360, w: 130, h: 18, starterProp: "pipes", propScale: 1.1 },
      { type: "prop", x: 2130, y: 880, w: 170, h: 40, starterProp: "fence_long", propScale: 1.15 },
      { type: "spark", x: 1435, y: 260 },
      { type: "spark", x: 1610, y: 260 },
    ],
    npcs: [
      {
        id: "printer",
        name: "Cynical Printer",
        x: 360,
        y: 790,
        w: 62,
        h: 50,
        portrait: "printer",
        lines: [
          "Paper jam was self-defense.",
          "Ride the belt. The crushers only respect timing and fear.",
        ],
      },
      {
        id: "flip",
        name: "Dead Flip Phone",
        x: 1890,
        y: 500,
        w: 32,
        h: 54,
        portrait: "phone",
        lines: [
          "One bar. One disk slot. That's your opening.",
          "Gate console wants old media. Very nostalgic of it.",
        ],
      },
    ],
    items: [
      {
        id: "floppy",
        kind: "pickup",
        x: 1948,
        y: 395,
        w: 32,
        h: 28,
        text: "Picked up a dusty floppy disk. Somehow it still matters.",
      },
    ],
    fragments: [
      { id: "frag-2", x: 920, y: 742, text: "Recovered memory: summer98_beach_photo.bmp" },
    ],
  },
  {
    id: "prove-you-still-work",
    label: "Prove You Still Work",
    title: "Let the graveyard hear you post.",
    hint: "Speak to the modem, then use the diagnostic console and pass the sequence test.",
    world: { width: 1760, height: 920 },
    start: { x: 200, y: 655 },
    checkpoint: { x: 200, y: 655, label: "Final chamber. The modem is waiting." },
    exitZone: { x: 1490, y: 335, w: 140, h: 220, toAct: "ending", requires: "diagnosticPassed" },
    console: { x: 860, y: 430, w: 92, h: 84 },
    gates: [
      {
        id: "final-gate",
        x: 1370,
        y: 300,
        w: 54,
        h: 270,
        opensWith: "diagnosticPassed",
      },
    ],
    solids: [
      { x: 0, y: 0, w: 1760, h: 120 },
      { x: 0, y: 0, w: 90, h: 920 },
      { x: 0, y: 830, w: 1760, h: 90 },
      { x: 1670, y: 0, w: 90, h: 920 },
      { x: 300, y: 340, w: 190, h: 62 },
      { x: 520, y: 250, w: 280, h: 56 },
      { x: 1010, y: 250, w: 300, h: 56 },
      { x: 610, y: 650, w: 440, h: 64 },
      { x: 1100, y: 640, w: 220, h: 70 },
    ],
    decor: [
      { type: "pile", x: 1180, y: 610, w: 160, h: 62 },
      { type: "scatter_scrap", x: 594, y: 690, w: 220, h: 46, count: 13 },
      { type: "scatter_scrap", x: 1120, y: 686, w: 190, h: 40, count: 11, colors: ["#58646d", "#6e7378", "#7b6750"] },
      { type: "pipe", x: 770, y: 365, w: 80, h: 18, starterProp: "pipes", propScale: 0.9 },
      { type: "prop", x: 1320, y: 720, w: 120, h: 70, starterProp: "trash_container", propScale: 1.1 },
      { type: "spark", x: 886, y: 330 },
      { type: "spark", x: 1260, y: 304 },
    ],
    npcs: [
      {
        id: "modem-return",
        name: "Wise Old Modem",
        x: 390,
        y: 470,
        w: 48,
        h: 48,
        portrait: "modem",
        lines: [
          "They confuse age with absence.",
          "Run the diagnostic clean and the exit should remember mercy.",
        ],
      },
    ],
    fragments: [
      { id: "frag-3", x: 1270, y: 700, text: "Recovered memory: letter_to_future_me.doc" },
    ],
  },
];

const cloneLevel = (baseIndex, overrides = {}) => {
  const level = JSON.parse(JSON.stringify(BASE_LEVELS[baseIndex]));
  const merged = {
    ...level,
    ...overrides,
    world: overrides.world ?? level.world,
    start: overrides.start ?? level.start,
    checkpoint: overrides.checkpoint ?? level.checkpoint,
    exitZone: overrides.exitZone ?? level.exitZone,
    socket: overrides.socket === undefined ? level.socket : overrides.socket,
    battery: overrides.battery === undefined ? level.battery : overrides.battery,
    gateConsole: overrides.gateConsole === undefined ? level.gateConsole : overrides.gateConsole,
    console: overrides.console === undefined ? level.console : overrides.console,
    gates: overrides.gates === undefined ? level.gates : overrides.gates,
    solids: overrides.solids === undefined ? level.solids : overrides.solids,
    decor: overrides.decor === undefined ? level.decor : overrides.decor,
    npcs: overrides.npcs === undefined ? level.npcs : overrides.npcs,
    fragments: overrides.fragments === undefined ? level.fragments : overrides.fragments,
    items: overrides.items === undefined ? level.items : overrides.items,
    hazards: overrides.hazards === undefined ? level.hazards : overrides.hazards,
    conveyors: overrides.conveyors === undefined ? level.conveyors : overrides.conveyors,
    checkpoints: overrides.checkpoints === undefined ? level.checkpoints : overrides.checkpoints,
    navigationMode: overrides.navigationMode ?? level.navigationMode,
    startNodeId: overrides.startNodeId ?? level.startNodeId,
    nodes: overrides.nodes === undefined ? level.nodes : overrides.nodes,
    edges: overrides.edges === undefined ? level.edges : overrides.edges,
    interactors: overrides.interactors === undefined ? level.interactors : overrides.interactors,
    structures: overrides.structures === undefined ? level.structures : overrides.structures,
    structureStates: overrides.structureStates === undefined ? level.structureStates : overrides.structureStates,
    cameraRig: overrides.cameraRig === undefined ? level.cameraRig : overrides.cameraRig,
  };
  return merged;
};

export const ACTS = [
  cloneLevel(0, {
    id: "cold-boot",
    chapter: 1,
    number: 1,
    label: "Cold Boot",
    title: "Wake, wobble, move.",
    hint: "Find a powered machine and figure out what still listens in the heap.",
    introLine: "Cold boot. Bad yard. Still mine to cross.",
    fragments: [],
    battery: null,
    socket: null,
    gates: [],
    solids: [
      { x: 0, y: 0, w: 1800, h: 120 },
      { x: 0, y: 0, w: 90, h: 920 },
      { x: 0, y: 830, w: 1800, h: 90 },
      { x: 1710, y: 0, w: 90, h: 920 },
      { x: 240, y: 250, w: 220, h: 70 },
      { x: 500, y: 355, w: 140, h: 72 },
      { x: 760, y: 605, w: 240, h: 82 },
      { x: 1110, y: 220, w: 220, h: 72 },
    ],
    decor: [
      { type: "pile", x: 260, y: 245, w: 180, h: 60 },
      { type: "scatter_scrap", x: 320, y: 694, w: 240, h: 58, count: 14 },
      { type: "scatter_scrap", x: 970, y: 670, w: 200, h: 52, count: 10 },
      { type: "prop", x: 1390, y: 750, w: 120, h: 70, starterProp: "trash_container", propScale: 1.15 },
      { type: "spark", x: 612, y: 292 },
    ],
    npcs: [
      {
        id: "crt",
        name: "Bitter CRT",
        x: 360,
        y: 565,
        w: 54,
        h: 54,
        portrait: "crt",
        lines: [
          "You booted? In this neighborhood? Bold.",
          "Find the modem. It still believes in current.",
        ],
      },
    ],
    exitZone: { x: 1490, y: 485, w: 120, h: 170, toAct: 1, requires: "act1TalkedToMachine" },
  }),
  cloneLevel(0, {
    id: "heap-talk",
    chapter: 1,
    number: 2,
    label: "Heap Talk",
    title: "Listen before the yard decides for you.",
    hint: "Talk to the machines, then line up the battery route.",
    introLine: "If the dead machines can talk, they can point me out.",
    fragments: [],
    start: { x: 520, y: 612 },
    checkpoint: { x: 520, y: 612, label: "Checkpoint: the heap starts speaking back." },
    npcs: [
      {
        id: "crt",
        name: "Bitter CRT",
        x: 360,
        y: 565,
        w: 54,
        h: 54,
        portrait: "crt",
        lines: [
          "You again. Good. Means the yard didn't win instantly.",
          "The battery is heavy, the socket is picky, and dawn is rude.",
        ],
      },
      {
        id: "modem",
        name: "Wise Old Modem",
        x: 665,
        y: 520,
        w: 48,
        h: 48,
        portrait: "modem",
        lines: [
          "Power the socket, little hinge. The gate still remembers electricity.",
          "Line up the charge. The path opens after that.",
        ],
      },
    ],
    exitZone: { x: 1585, y: 490, w: 120, h: 180, toAct: 2, requires: "batterySocketPowered" },
  }),
  cloneLevel(0, {
    id: "socket-run",
    chapter: 1,
    number: 3,
    label: "Socket Run",
    title: "Push charge back into the yard.",
    hint: "Restore the socket, crack the gate, and reach the shredder line.",
    introLine: "Charge first. Escape second.",
    fragments: [],
    start: { x: 820, y: 640 },
    checkpoint: { x: 820, y: 640, label: "Checkpoint: one shove from a live socket." },
    npcs: [],
    exitZone: { x: 1585, y: 490, w: 120, h: 180, toAct: 3, requires: "batterySocketPowered" },
  }),
  cloneLevel(1, {
    id: "belt-ride",
    chapter: 2,
    number: 4,
    label: "Belt Ride",
    title: "Let the line move under you.",
    hint: "Catch the conveyor and survive the first stretch.",
    introLine: "That shredder line is moving. So am I.",
    enterCutscene: "act2Intro",
    gateConsole: null,
    gates: [],
    items: [],
    fragments: [],
    hazards: [],
    checkpoints: [
      { id: "cp-4a", x: 240, y: 860, radius: 70, label: "Checkpoint: line caught." },
      { id: "cp-4b", x: 930, y: 840, radius: 72, label: "Checkpoint: belt still under you." },
    ],
    exitZone: { x: 2280, y: 310, w: 90, h: 210, toAct: 4 },
  }),
  cloneLevel(1, {
    id: "crusher-alley",
    chapter: 2,
    number: 5,
    label: "Crusher Alley",
    title: "Timing is dignity with moving parts.",
    hint: "Cross the crushers cleanly and keep heading right.",
    introLine: "Those arms only hit what hesitates.",
    gateConsole: null,
    gates: [],
    items: [],
    fragments: [],
    start: { x: 1180, y: 820 },
    checkpoint: { x: 1180, y: 820, label: "Checkpoint: crusher alley ahead." },
    conveyors: [],
    exitZone: { x: 2280, y: 310, w: 90, h: 210, toAct: 5 },
  }),
  cloneLevel(1, {
    id: "floppy-hunt",
    chapter: 2,
    number: 6,
    label: "Floppy Hunt",
    title: "Find the square little miracle.",
    hint: "Grab the floppy disk and hold onto it.",
    introLine: "One dusty disk between me and the next gate.",
    gateConsole: null,
    gates: [],
    fragments: [],
    start: { x: 1715, y: 740 },
    checkpoint: { x: 1715, y: 740, label: "Checkpoint: disk should be close." },
    checkpoints: [],
    hazards: [
      {
        id: "crusher-b",
        x: 1545,
        y: 250,
        w: 84,
        h: 120,
        travel: 310,
        speed: 1.9,
        phase: 1.8,
      },
    ],
    exitZone: { x: 2280, y: 310, w: 90, h: 210, toAct: 6 },
  }),
  cloneLevel(1, {
    id: "gate-feed",
    chapter: 2,
    number: 7,
    label: "Gate Feed",
    title: "Feed the past into the console.",
    hint: "Use the floppy disk at the gate console and move on.",
    introLine: "Legacy media. Legacy problems. Fine.",
    start: { x: 1945, y: 410 },
    checkpoint: { x: 1945, y: 410, label: "Checkpoint: console in sight." },
    hazards: [],
    conveyors: [],
    exitZone: { x: 2280, y: 310, w: 90, h: 210, toAct: 7, requires: "act2GateOpen" },
  }),
  cloneLevel(1, {
    id: "fence-maze",
    chapter: 3,
    number: 8,
    label: "Fence Maze",
    title: "The deep yard tangles inward.",
    hint: "Weave through the fenced route and keep the momentum alive.",
    introLine: "The gate opened. The yard just got meaner.",
    gateConsole: null,
    gates: [],
    items: [],
    fragments: [],
    exitZone: { x: 2280, y: 310, w: 90, h: 210, toAct: 8 },
  }),
  cloneLevel(0, {
    id: "signal-stair",
    chapter: 3,
    number: 9,
    label: "Signal Stair",
    title: "A path only exists when the old bridge agrees to it.",
    hint: "Tap a node to walk. Tap the spindle to rotate the bridge toward the modem shrine.",
    introLine: "The yard goes quiet here. Even the rust feels ceremonial.",
    navigationMode: "graph",
    world: { width: 980, height: 1400 },
    start: { x: 458, y: 1188 },
    checkpoint: { x: 458, y: 1188, label: "Checkpoint: the stair remembers your weight." },
    startNodeId: "entry",
    cameraRig: {
      mode: "anchored",
      focus: { x: 490, y: 760 },
      deadZone: 110,
      followStrength: 0.18,
    },
    socket: null,
    battery: null,
    gateConsole: null,
    console: null,
    gates: [],
    solids: [],
    hazards: [],
    conveyors: [],
    checkpoints: [],
    fragments: [],
    items: [],
    npcs: [
      {
        id: "modem",
        name: "Wise Old Modem",
        x: 462,
        y: 196,
        w: 48,
        h: 48,
        portrait: "modem",
        lines: [
          "Turn the spindle until the bridge remembers you.",
          "Some roads only exist for patient machines.",
        ],
      },
    ],
    decor: [
      { type: "prop", x: 408, y: 1088, w: 140, h: 80, starterProp: "trash_container", propScale: 0.72 },
      { type: "prop", x: 406, y: 164, w: 150, h: 92, starterProp: "cardboard_boxes", propScale: 0.62 },
      { type: "spark", x: 492, y: 742 },
      { type: "spark", x: 492, y: 266 },
    ],
    structures: [
      {
        id: "bridgeA",
        type: "rotating-bridge",
        x: 490,
        y: 760,
        span: 236,
        baseHeight: 1.28,
      },
    ],
    structureStates: {
      bridgeA: "east",
    },
    interactors: [
      {
        id: "bridgeA-rotator",
        x: 490,
        y: 920,
        radius: 64,
        label: "Rotate the spindle bridge",
        target: "bridgeA",
        cycle: ["east", "north"],
      },
    ],
    nodes: [
      { id: "entry", x: 490, y: 1188, kind: "path" },
      { id: "lower-landing", x: 490, y: 1010, kind: "path" },
      { id: "bridge-hub", x: 490, y: 760, kind: "junction" },
      { id: "east-landing", x: 726, y: 760, kind: "deadend" },
      { id: "upper-landing", x: 490, y: 510, kind: "path" },
      { id: "modem-shrine", x: 490, y: 260, kind: "goal" },
    ],
    edges: [
      { from: "entry", to: "lower-landing" },
      { from: "lower-landing", to: "bridge-hub" },
      { from: "bridge-hub", to: "east-landing", requiresState: { bridgeA: "east" } },
      { from: "bridge-hub", to: "upper-landing", requiresState: { bridgeA: "north" } },
      { from: "upper-landing", to: "modem-shrine" },
    ],
    exitZone: { x: 432, y: 170, w: 118, h: 130, toAct: 9 },
  }),
  cloneLevel(0, {
    id: "modem-relay",
    chapter: 3,
    number: 10,
    label: "Modem Relay",
    title: "The old network still remembers you.",
    hint: "Meet the modem again and push on to the diagnostic wing.",
    introLine: "Static means memory. Memory means a way forward.",
    socket: null,
    battery: null,
    gates: [],
    fragments: [],
    exitZone: { x: 1585, y: 490, w: 120, h: 180, toAct: 10 },
  }),
  cloneLevel(2, {
    id: "diagnostic-hall",
    chapter: 4,
    number: 11,
    label: "Diagnostic Hall",
    title: "One last indignity before sunrise.",
    hint: "Reach the console chamber and prepare to prove you still work.",
    introLine: "One more test. Then no one gets to call me dead.",
    enterCutscene: "act3Intro",
    fragments: [],
    exitZone: { x: 1490, y: 335, w: 140, h: 220, toAct: 11, requires: "diagnosticPassed" },
  }),
  cloneLevel(2, {
    id: "post-trial",
    chapter: 4,
    number: 12,
    label: "POST Trial",
    title: "Pass the sequence. Earn the exit.",
    hint: "Use the diagnostic console and clear all three rounds.",
    introLine: "Post clean. Leave loud.",
    fragments: [],
    exitZone: { x: 1490, y: 335, w: 140, h: 220, toAct: 12, requires: "diagnosticPassed" },
  }),
  cloneLevel(2, {
    id: "dawn-escape",
    chapter: 4,
    number: 13,
    label: "Dawn Escape",
    title: "The route is open. Take it.",
    hint: "Run for the last door and refuse the scrap heap one final time.",
    introLine: "Sunrise is close enough to hear.",
    fragments: [],
    exitZone: { x: 1490, y: 335, w: 140, h: 220, toAct: "ending", requires: "diagnosticPassed" },
  }),
];
